backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'site/content/home.json'
        fields:
          - label: Suffixes
            name: suffixes
            widget: list
            field: { label: Suffix, name: suffix, widget: string }
          - label: Middle
            name: middle
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Subtitle, name: subtitle, widget: string }
          - label: End
            name: end
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Subtitle, name: subtitle, widget: string }
      - label: 'About'
        name: 'about'
        file: 'site/content/about.json'
        fields:
          - label: Title
            name: title
            widget: string
          - label: Description
            name: description
            widget: text
          - label: Links
            name: links
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Icon, name: icon, widget: string }
              - { label: Url, name: url, widget: string }