backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'site/content/home.json'
        fields:
          - label: Suffixes
            name: suffixes
            widget: list
            field: { label: Suffix, name: suffix, widget: string }
          - label: Middle
            name: middle
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Subtitle, name: subtitle, widget: string }
          - label: End
            name: end
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Subtitle, name: subtitle, widget: string }
      - label: 'About'
        name: 'about'
        file: 'site/content/about.json'
        fields:
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Description
            name: description
            widget: text
          - label: Profile Image
            name: profileImage
            widget: image
          - label: Under Profile Image
            name: underProfileImage
            widget: image
          - label: Profile Alt
            name: profileAlt
            widget: text
          - label: Links
            name: links
            widget: list
            fields:
              - { label: Icon, name: icon, widget: string }
              - { label: Url, name: url, widget: string }
      - label: 'Blog'
        name: 'blog'
        file: 'site/content/blog.json'
        fields:
          - label: Title
            name: title
            widget: string
          - label: Description
            name: description
            widget: text
      - label: 'Error'
        name: 'error'
        file: 'site/content/error.json'
        fields:
          - label: Title
            name: title
            widget: string
      - label: 'Portfolio'
        name: 'portfolio'
        file: 'site/content/portfolio.json'
        fields:
          - label: Title
            name: title
            widget: string
          - label: Description
            name: description
            widget: text
      - label: 'Error'
        name: 'error'
        file: 'site/content/error.json'
        fields:
          - label: Title
            name: title
            widget: string
  - label: 'Blog'
    name: 'blog'
    folder: 'site/blog'
    extension: json
    format: json
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - label: Featured Image
        name: image
        widget: object
        fields:
          - { label: Image, name: url, widget: image }
          - { label: Alt, name: alt, widget: string }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
