backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "site/content/home.md"
        fields:
          - label: Suffixes
            name: suggix
            widget: list
            fields:
              - {label: Suffix, name: suffix, widget: string}